const API='https://ps99.biggamesapi.io';
const state={pets:[],view:'market',category:'all',variant:'all',sort:'potential',search:'',min:0,max:0,tracked:true,positive:false,highPotential:false,limit:48,compact:false};
const favs=new Set(JSON.parse(localStorage.getItem('ps99-favs-v3')||'[]')); const compare=new Set(); let currentPet=null;
const $=id=>document.getElementById(id); const fmt=n=>{n=Number(n||0); if(!n)return '—'; const u=[[1e15,'Q'],[1e12,'T'],[1e9,'B'],[1e6,'M'],[1e3,'K']]; for(const [v,s] of u)if(n>=v)return (n/v).toLocaleString('de-DE',{maximumFractionDigits:2})+s;return n.toLocaleString('de-DE')};
const pct=n=>n==null?'—':`${n>=0?'+':''}${n.toFixed(1)}%`; const key=p=>`${p.id}|${p.variant}|${p.shiny?'1':'0'}`;
const imgFallback='data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%22180%22 height=%22180%22%3E%3Crect width=%22180%22 height=%22180%22 rx=%2230%22 fill=%22%23101a2c%22/%3E%3Ctext x=%2250%25%22 y=%2255%25%22 text-anchor=%22middle%22 fill=%22%2394a3b8%22 font-size=%2214%22 font-family=%22Arial%22%3EPS99%3C/text%3E%3C/svg%3E';
async function api(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status}`);return r.json()}
function escape(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function variantLabel(p){if(p.shiny&&p.variant==='gold')return'Shiny Golden';if(p.shiny&&p.variant==='rainbow')return'Shiny Rainbow';if(p.shiny)return'Shiny';if(p.variant==='gold')return'Golden';if(p.variant==='rainbow')return'Rainbow';return'Normal'}
function renderCards(){let ps=filtered();$('results').textContent=ps.length.toLocaleString('de-DE');$('grid').innerHTML=ps.slice(0,state.limit).map(card).join('');$('loadMore').classList.toggle('hidden',state.limit>=ps.length);$('empty').classList.toggle('hidden',ps.length>0);bindCards()}
function filtered(){let q=state.search.toLowerCase();let ps=state.pets.filter(p=>{if(state.view==='watchlist'&&!favs.has(key(p)))return false;if(state.category!=='all'&&p.category!==state.category)return false;if(state.variant==='shiny'&&!p.shiny)return false;if(state.variant!=='all'&&state.variant!=='shiny'&&p.variant!==state.variant)return false;if(q&&!`${p.name} ${p.id} ${p.category}`.toLowerCase().includes(q))return false;if(state.tracked&&!p.rap)return false;if(state.min&&p.rap<state.min)return false;if(state.max&&p.rap>state.max)return false;if(state.positive&&(p.move24||0)<=0)return false;if(state.highPotential&&(p.potential||0)<70)return false;return true});return ps.sort((a,b)=>{switch(state.sort){case'move':return(b.move24||0)-(a.move24||0);case'rapAsc':return a.rap-b.rap;case'rapDesc':return b.rap-a.rap;case'existsAsc':return a.exists-b.exists;case'existsDesc':return b.exists-a.exists;case'name':return a.name.localeCompare(b.name);default:return(b.potential||0)-(a.potential||0)}})}
function card(p){const k=key(p);const img=p.image||imgFallback;return `<article class="pet-card" data-open="${encodeURIComponent(k)}"><button class="pet-compare ${compare.has(k)?'active':''}" data-compare="${encodeURIComponent(k)}">⇄</button><button class="pet-fav ${favs.has(k)?'active':''}" data-fav="${encodeURIComponent(k)}">★</button><div class="pet-art"><img src="${img}" alt="${escape(p.name)}" loading="lazy" onerror="this.src='${imgFallback}'"></div><div class="pet-info"><div class="pet-title"><div class="pet-name" title="${escape(p.name)}">${escape(p.name)}</div><span class="variant-tag">${variantLabel(p)}</span></div><div class="pet-sub"><span class="pill">${escape(p.category||'Pet')}</span><span class="pill">${fmt(p.exists)} exists</span>${p.obtainable===false?'<span class="pill">Index</span>':''}</div><div class="potential"><div class="potential-head"><span>Potential</span><b>${p.potential||0}/100</b></div><div class="potential-bar"><span style="width:${Math.max(2,p.potential||0)}%"></span></div></div><div class="numbers"><div class="num"><small>RAP</small><b>${fmt(p.rap)} 💎</b></div><div class="num"><small>24h</small><b class="${(p.move24||0)>=0?'good':'bad'}">${pct(p.move24)}</b></div></div></div></article>`}
function bindCards(){}
function $$(s){return document.querySelectorAll(s)}
document.addEventListener('click',e=>{const fav=e.target.closest('[data-fav]');if(fav){const k=decodeURIComponent(fav.dataset.fav);favs.has(k)?favs.delete(k):favs.add(k);localStorage.setItem('ps99-favs-v3',JSON.stringify([...favs]));renderCards();renderCompareBar();return}const cmp=e.target.closest('[data-compare]');if(cmp){const k=decodeURIComponent(cmp.dataset.compare);if(compare.has(k))compare.delete(k);else if(compare.size<3)compare.add(k);else return toast('Maximal 3 Pets vergleichen');renderCards();renderCompareBar();return}const open=e.target.closest('[data-open]');if(open&&!e.target.closest('button'))openDetail(decodeURIComponent(open.dataset.open))});
function getByKey(k){return state.pets.find(p=>key(p)===k)}
function renderFeatured(){const top=[...state.pets].filter(p=>p.rap).sort((a,b)=>b.potential-a.potential).slice(0,3);$('featured').innerHTML=top.map(p=>`<div class="feature" data-open="${encodeURIComponent(key(p))}"><div class="feature-top"><div><div class="feature-name">${escape(p.name)}</div><small>Potential ${p.potential}/100 · ${variantLabel(p)}</small></div><span class="${p.move24>=0?'good':'bad'}">${pct(p.move24)}</span></div><div class="metric">${fmt(p.rap)} 💎</div></div>`).join('')}
function dashboard(){const ps=state.pets.filter(p=>p.rap);const gain=[...ps].sort((a,b)=>(b.move24||0)-(a.move24||0))[0],lose=[...ps].sort((a,b)=>(a.move24||0)-(b.move24||0))[0],pot=[...ps].sort((a,b)=>b.potential-a.potential)[0],scar=[...ps].filter(p=>p.exists).sort((a,b)=>a.exists-b.exists)[0];const avg=ps.length?ps.reduce((s,p)=>s+(p.move24||0),0)/ps.length:0;$('marketPulse').textContent=pct(avg);$('marketPulse').className='big-num '+(avg>=0?'good':'bad');$('topGainer').textContent=gain?.name||'—';$('topGainerMove').textContent=pct(gain?.move24);$('topGainerMove').className=(gain?.move24||0)>=0?'good':'bad';$('topLoser').textContent=lose?.name||'—';$('topLoserMove').textContent=pct(lose?.move24);$('topLoserMove').className=(lose?.move24||0)>=0?'good':'bad';$('topPotential').textContent=pot?.name||'—';$('topPotentialScore').textContent=pot?`${pot.potential}/100`:'—';$('mostScarce').textContent=scar?.name||'—';$('mostScarceExists').textContent=scar?`${fmt(scar.exists)} exists`:'—';$('petCount').textContent=state.pets.length.toLocaleString('de-DE');$('trackedCount').textContent=ps.length.toLocaleString('de-DE')}
function renderCompareBar(){const bar=$('compareBar');bar.classList.toggle('hidden',compare.size===0);$('compareCount').textContent=`${compare.size}/3`;$('compareItems').innerHTML=[...compare].map(k=>`<span class="compare-chip">${escape(getByKey(k)?.name||k)}</span>`).join('')}
function drawChart(series){const pts=series.filter(x=>x.rap>0);if(pts.length<2)return'<div class="detail-muted">Noch nicht genug gespeicherte Snapshots. Sobald der Tracker läuft, wird die echte 24h-Historie aufgebaut.</div>';const w=560,h=190,pad=22,min=Math.min(...pts.map(x=>x.rap)),max=Math.max(...pts.map(x=>x.rap));const den=max-min||1;const poly=pts.map((x,i)=>`${pad+i*((w-pad*2)/(pts.length-1))},${h-pad-((x.rap-min)/den)*(h-pad*2)}`).join(' ');const area=`${pad},${h-pad} ${poly} ${w-pad},${h-pad}`;return `<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#8c67ff" stop-opacity=".35"/><stop offset="1" stop-color="#8c67ff" stop-opacity="0"/></linearGradient></defs><polyline points="${area}" fill="url(#g)" stroke="none"/><polyline points="${poly}" fill="none" stroke="#9e86ff" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/><line x1="22" y1="168" x2="538" y2="168" stroke="#223149"/><text x="22" y="181" fill="#71819a" font-size="9">24h</text><text x="538" y="181" text-anchor="end" fill="#71819a" font-size="9">Jetzt</text></svg>`}
async function openDetail(k){const p=getByKey(k);if(!p)return;currentPet=p;$('drawer').classList.add('open');$('drawer').setAttribute('aria-hidden','false');$('detail').innerHTML='<div class="detail"><div style="color:#8191a7">Lade Marktanalyse…</div></div>';try{const v=await api(`/api/pet?id=${encodeURIComponent(p.id)}&variant=${p.variant}&shiny=${p.shiny?'1':'0'}`);const m=v.metrics;const insight=m.potential>=70?'Momentum + Knappheit sprechen aktuell eher für Beobachten/Watchlist.':m.move24>3?'Klarer positiver Momentum-Impuls in den gespeicherten Snapshots.':m.move24<-3?'Negatives Momentum – eher nicht blind hinterherkaufen.':'Kein klarer Trend; auf weitere Snapshots warten.';$('detail').innerHTML=`<div class="detail"><div class="detail-hero"><div class="detail-img"><img src="${p.image||imgFallback}" onerror="this.src='${imgFallback}'"></div><div><h2>${escape(p.name)}</h2><div class="detail-muted">${escape(p.desc||'Pet Simulator 99 Market Data')}</div><div class="detail-tags"><span>${escape(p.category||'Pet')}</span><span>${variantLabel(p)}</span><span>${fmt(p.exists)} exists</span></div></div></div><div class="detail-metrics"><div class="metric-card"><small>AKTUELLER RAP</small><b>${fmt(p.rap)} 💎</b></div><div class="metric-card"><small>24H CHANGE</small><b class="${(m.move24||0)>=0?'good':'bad'}">${pct(m.move24)}</b></div><div class="metric-card"><small>POTENTIAL</small><b>${m.potential}/100</b></div></div><div class="chart-box"><div class="chart-head"><b>RAP Verlauf</b><span class="detail-muted">${v.historyAvailable?`${v.snapshotCount} Snapshots gespeichert`:'Historie baut sich auf'}</span></div><div class="chart">${drawChart(v.series)}</div></div><div class="detail-grid"><div class="insight"><b>Warum dieser Score?</b><p>Momentum: ${Math.round(50+((m.move24||0)*2.5))}/100 · Knappheit: ${Math.round(m.scarcity)}/100 · Beschleunigung: ${m.acceleration==null?'—':pct(m.acceleration)}.</p></div><div class="insight"><b>Markt-Note</b><p>${insight}</p></div></div></div>`}catch(e){$('detail').innerHTML=`<div class="detail"><h2>${escape(p.name)}</h2><p class="detail-muted">Detaildaten konnten nicht geladen werden. Prüfe, ob der Node-Server läuft.</p></div>`}}
function closeDetail(){$('drawer').classList.remove('open');$('drawer').setAttribute('aria-hidden','true')}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
function setup(){for(const id of ['search','minRap','maxRap'])$(id).addEventListener('input',()=>{state.search=$('search').value.trim();state.min=Number($('minRap').value||0);state.max=Number($('maxRap').value||0);state.limit=48;renderCards()});$('tracked').addEventListener('change',e=>{state.tracked=e.target.checked;state.limit=48;renderCards()});$('positive').addEventListener('change',e=>{state.positive=e.target.checked;state.limit=48;renderCards()});$('highPotential').addEventListener('change',e=>{state.highPotential=e.target.checked;state.limit=48;renderCards()});$('sort').addEventListener('change',e=>{state.sort=e.target.value;renderCards()});[['category','category'],['variant','variant']].forEach(([id,field])=>$(id).addEventListener('click',e=>{if(!e.target.dataset.v)return;state[field]=e.target.dataset.v;$$(`#${id} button`).forEach(b=>b.classList.toggle('active',b.dataset.v===state[field]));state.limit=48;renderCards()}));$('loadMore').onclick=()=>{state.limit+=48;renderCards()};$('resetBtn').onclick=()=>{state.category='all';state.variant='all';state.sort='potential';state.search='';state.min=0;state.max=0;state.tracked=true;state.positive=false;state.highPotential=false;state.limit=48;['search','minRap','maxRap'].forEach(i=>$(i).value='');$('tracked').checked=true;$('positive').checked=false;$('highPotential').checked=false;$('sort').value='potential';$$('.chips button').forEach(b=>b.classList.toggle('active',b.dataset.v==='all'));renderCards()};$('refreshBtn').onclick=load;$('closeDrawer').onclick=closeDetail;$('.drawer-backdrop').onclick=closeDetail;$('themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('ps99-theme',document.body.classList.contains('light')?'light':'dark')};$('viewBtn').onclick=()=>{document.body.classList.toggle('compact-grid');state.compact=!state.compact;toast(state.compact?'Kompaktere Ansicht':'Normale Ansicht')};$$('.nav-btn').forEach(b=>b.onclick=()=>{$$('.nav-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.view=b.dataset.view;state.limit=48;renderCards()});$('findBtn').onclick=()=>{state.sort='potential';$('sort').value='potential';state.highPotential=false;renderCards();window.scrollTo({top:650,behavior:'smooth'})};$('compareBtn').onclick=()=>{if(compare.size<2)toast('Wähle 2–3 Pets mit ⇄ aus');else openCompare()};$('compareOpen').onclick=openCompare;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDetail();if(e.key==='/'&&document.activeElement!==$('search')){e.preventDefault();$('search').focus()}})}
function openCompare(){const ps=[...compare].map(getByKey).filter(Boolean);if(ps.length<2)return;toast('Vergleich: '+ps.map(p=>p.name).join(' · '))}
async function load(){ $('status').textContent='Updating';try{const d=await api('/api/data');state.pets=d.pets||[];$('snapshotCount').textContent=d.snapshotCount||0;$('footerTime').textContent=new Date(d.updatedAt).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'});$('status').textContent='Live';dashboard();renderFeatured();renderCards();renderCompareBar()}catch(e){$('status').textContent='Offline';toast('Server/API nicht erreichbar – starte node server.js')}}
if(localStorage.getItem('ps99-theme')==='light')document.body.classList.add('light');setup();load();setInterval(load,30*60*1000);
