let allPets = [], visible = [], shown = 48;
let state = { category:'all', variant:'normal', sort:'potential-desc', favOnly:false };
const favorites = new Set(JSON.parse(localStorage.getItem('ps99-favs') || '[]'));
const API = '';
const $ = id => document.getElementById(id);
const els = {grid:$('grid'), loading:$('loading'), error:$('errorBox'), loadMore:$('loadMoreBtn'), search:$('searchInput'), minRap:$('minRap'), maxRap:$('maxRap'), sort:$('sortSelect'), resultCount:$('resultCount'), petCount:$('petCount'), lastUpdated:$('lastUpdated'), status:$('statusPill'), refresh:$('refreshBtn'), clear:$('clearBtn'), favOnly:$('favOnlyBtn'), modal:$('petModal'), modalBody:$('modalBody'), closeModal:$('closeModal'), topMovers:$('topMovers'), topPotential:$('topPotential')};
function fmt(n){n=Number(n||0);if(!n)return '–';const u=[[1e15,'Q'],[1e12,'T'],[1e9,'B'],[1e6,'M'],[1e3,'K']];for(const[v,s]of u)if(n>=v)return`${(n/v).toLocaleString('de-DE',{maximumFractionDigits:2})}${s}`;return n.toLocaleString('de-DE')}
function pct(n){return n==null?'–':`${n>=0?'+':''}${n.toFixed(1)}%`}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function keyFor(p){return `${p.id}|${p.variant}|${p.shiny?'shiny':'normal'}`}
function variantLabel(p){if(p.shiny)return'Shiny';if(p.variant==='gold')return'Golden';if(p.variant==='rainbow')return'Rainbow';return'Normal'}
function card(p){const k=keyFor(p),fav=favorites.has(k);const move=p.move24;return`<article class="pet-card" data-id="${encodeURIComponent(p.id)}" data-variant="${p.variant}" data-shiny="${p.shiny?1:0}"><button class="fav ${fav?'active':''}" data-fav="${encodeURIComponent(k)}">★</button><div class="pet-image"><img src="${p.image||''}" alt="${escapeHtml(p.name)}" loading="lazy"></div><div class="pet-body"><div class="pet-name">${escapeHtml(p.name)}</div><div class="pet-meta"><span class="tag">${escapeHtml(p.category||'Pet')}</span><span class="tag ${p.variant==='gold'?'gold':''} ${p.shiny?'shiny':''}">${variantLabel(p)}</span></div><div class="values"><div class="value-box"><small>RAP</small><b>${fmt(p.rap)} 💎</b></div><div class="value-box"><small>24h</small><b class="${move>0?'good':move<0?'bad':''}">${pct(move)}</b></div></div><div class="potential-row"><span>Steig-Potenzial</span><strong>${p.potential ?? '–'}/100</strong></div><div class="potential-bar"><i style="width:${Math.max(0,Math.min(100,p.potential||0))}%"></i></div></div></article>`}
function apply(){const q=els.search.value.trim().toLowerCase(),min=Number(els.minRap.value||0),max=Number(els.maxRap.value||0);visible=allPets.filter(p=>{if(state.category!=='all'&&p.category!==state.category)return false;if(state.variant!=='normal'&&p.variant!==state.variant)return false;if(state.variant==='normal'&&p.shiny)return false;if(state.favOnly&&!favorites.has(keyFor(p)))return false;if(q&&!`${p.name} ${p.id} ${p.category}`.toLowerCase().includes(q))return false;if($('onlyTracked').checked&&!p.rap)return false;if(min&&p.rap<min)return false;if(max&&p.rap>max)return false;return true});visible.sort((a,b)=>({['rap-desc']:b.rap-a.rap,['exists-desc']:b.exists-a.exists,['exists-asc']:a.exists-b.exists,['move-desc']:(b.move24||-999)-(a.move24||-999),['move-asc']:(a.move24||999)-(b.move24||999),['name-asc']:a.name.localeCompare(b.name)}[state.sort]??((b.potential||0)-(a.potential||0))));shown=48;render()}
function render(){els.resultCount.textContent=visible.length.toLocaleString('de-DE');els.grid.innerHTML=visible.slice(0,shown).map(card).join('');els.loadMore.classList.toggle('hidden',shown>=visible.length);els.loading.classList.add('hidden');els.grid.querySelectorAll('.pet-card').forEach(c=>c.addEventListener('click',e=>{if(e.target.closest('[data-fav]'))return;openPet(decodeURIComponent(c.dataset.id),c.dataset.variant,c.dataset.shiny==='1')}));els.grid.querySelectorAll('[data-fav]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();const k=decodeURIComponent(b.dataset.fav);favorites.has(k)?favorites.delete(k):favorites.add(k);localStorage.setItem('ps99-favs',JSON.stringify([...favorites]));apply()}))}
async function openPet(id,variant,shiny){els.modal.classList.remove('hidden');els.modalBody.innerHTML='<div class="detail-loading">Lade 24h-Historie…</div>';try{const r=await fetch(`/api/pet?id=${encodeURIComponent(id)}&variant=${variant}&shiny=${shiny?1:0}`);const d=await r.json();if(!r.ok)throw new Error(d.error||'Fehler');els.modalBody.innerHTML=detailHtml(d)}catch(e){els.modalBody.innerHTML=`<div class="error card">${escapeHtml(e.message)}</div>`}}
function detailHtml(d){const p=d.pet,m=d.metrics,series=d.series||[];const labels=series.map(x=>new Date(x.ts).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'}));const pts=series.map(x=>x.rap);const chart=makeChart(pts,labels);const confidence=Math.min(100,Math.round((series.length/48)*100));return`<div class="detail-head"><img src="${p.image}" alt="${escapeHtml(p.name)}"><div><div class="eyebrow">PET DETAIL</div><h2>${escapeHtml(p.name)}</h2><div class="pet-meta"><span class="tag">${escapeHtml(p.category)}</span><span class="tag">${variantLabel(p)}</span></div><div class="detail-rap">${fmt(m.now)} 💎 <span class="${m.move24>=0?'good':'bad'}">${pct(m.move24)} / 24h</span></div></div></div><div class="stats-grid"><div><small>24h Start</small><b>${fmt(m.old)} 💎</b></div><div><small>Aktuell</small><b>${fmt(m.now)} 💎</b></div><div><small>Exists</small><b>${fmt(p.exists)}</b></div><div><small>Potenzial</small><b>${m.potential}/100</b></div></div><div class="chart-card"><div class="chart-title"><span>RAP · letzte 24h</span><span>${series.length} Snapshots</span></div>${chart}</div><div class="potential-card"><div><strong>${m.label}</strong><p>Heuristischer Score aus 24h-Momentum, Trend-Beschleunigung, Exists-Knappheit und Pet-Kategorie. Kein garantierter Gewinn.</p></div><div class="score">${m.potential}</div></div><div class="confidence"><span>Historien-Abdeckung</span><b>${confidence}%</b><div class="potential-bar"><i style="width:${confidence}%"></i></div></div>`}
function makeChart(values,labels){if(!values.length)return'<div class="no-history">Noch keine Historie vorhanden. Nach dem ersten Snapshot wird sie aufgebaut.</div>';const w=920,h=300,p=30,min=Math.min(...values),max=Math.max(...values),range=max-min||1;const pts=values.map((v,i)=>`${p+(i/(Math.max(values.length-1,1)))*(w-p*2)},${h-p-((v-min)/range)*(h-p*2)}`).join(' ');const last=values.at(-1),first=values[0],up=last>=first;return`<svg class="chart" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-opacity=".35"/><stop offset="1" stop-opacity="0"/></linearGradient></defs><polyline points="${pts}" fill="none" stroke="${up?'#42e89b':'#ff5e78'}" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><polyline points="${p},${h-p} ${pts} ${w-p},${h-p}" fill="url(#area)" stroke="none"/><text x="${p}" y="20">${escapeHtml(new Date(seriesTime()).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'}))}</text><text x="${w-p}" y="20" text-anchor="end">${fmt(max)}</text></svg>`}
function seriesTime(){return Date.now()-24*60*60*1000}
function topLists(){const movers=[...allPets].sort((a,b)=>(b.move24||-999)-(a.move24||-999)).slice(0,5);const potential=[...allPets].sort((a,b)=>(b.potential||0)-(a.potential||0)).slice(0,5);els.topMovers.innerHTML=movers.map(p=>mini(p,pct(p.move24))).join('');els.topPotential.innerHTML=potential.map(p=>mini(p,`${p.potential}/100`)).join('')}
function mini(p,right){return`<button class="mini-pet" data-id="${encodeURIComponent(p.id)}" data-variant="${p.variant}" data-shiny="${p.shiny?1:0}"><img src="${p.image}" alt=""><span><b>${escapeHtml(p.name)}</b><small>${fmt(p.rap)} 💎</small></span><strong>${right}</strong></button>`}
async function load(){els.status.textContent='Live-Daten werden geladen…';els.status.className='status-pill loading';els.loading.classList.remove('hidden');try{const r=await fetch('/api/data');const d=await r.json();if(!r.ok)throw new Error(d.error||'API-Fehler');allPets=d.pets;els.petCount.textContent=allPets.length.toLocaleString('de-DE');els.lastUpdated.textContent=new Date(d.updatedAt).toLocaleString('de-DE',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'2-digit'});els.status.textContent=`Live · ${d.snapshotCount} Snapshots`;els.status.className='status-pill ok';apply();topLists()}catch(e){els.loading.classList.add('hidden');els.error.classList.remove('hidden');els.error.innerHTML=`<strong>Daten konnten nicht geladen werden.</strong><br>${escapeHtml(e.message)}<br><br>Starte die Website über <code>node server.js</code>.`;els.status.textContent='Offline';els.status.className='status-pill loading'}}
['input','change'].forEach(ev=>{els.search.addEventListener(ev,apply);els.minRap.addEventListener(ev,apply);els.maxRap.addEventListener(ev,apply);$('onlyTracked').addEventListener(ev,apply)});
$('categoryFilter').addEventListener('click',e=>{if(e.target.dataset.value){state.category=e.target.dataset.value;toggleActive('categoryFilter',state.category);apply()}});$('variantFilter').addEventListener('click',e=>{if(e.target.dataset.value){state.variant=e.target.dataset.value;toggleActive('variantFilter',state.variant);apply()}});els.sort.addEventListener('change',()=>{state.sort=els.sort.value;apply()});els.clear.addEventListener('click',()=>{els.search.value='';els.minRap.value='';els.maxRap.value='';$('onlyTracked').checked=true;state={category:'all',variant:'normal',sort:'potential-desc',favOnly:false};els.sort.value='potential-desc';toggleActive('categoryFilter','all');toggleActive('variantFilter','normal');els.favOnly.classList.remove('active');apply()});els.favOnly.addEventListener('click',()=>{state.favOnly=!state.favOnly;els.favOnly.classList.toggle('active',state.favOnly);apply()});els.loadMore.addEventListener('click',()=>{shown+=48;render()});els.refresh.addEventListener('click',()=>fetch('/api/refresh').then(load));els.closeModal.addEventListener('click',()=>els.modal.classList.add('hidden'));els.modal.addEventListener('click',e=>{if(e.target===els.modal)els.modal.classList.add('hidden')});document.addEventListener('keydown',e=>{if(e.key==='Escape')els.modal.classList.add('hidden')});document.addEventListener('click',e=>{const b=e.target.closest('.mini-pet');if(b)openPet(decodeURIComponent(b.dataset.id),b.dataset.variant,b.dataset.shiny==='1')});
load();setInterval(load,30*60*1000);
